Repository projectsyn/component-backup-k8up, pull requests merged in 2021-07, with the labels that each got.

#31 Cleanup and simplify image parameter config and docs
  class/defaults.yml
  docs/modules/ROOT/pages/how-tos/upgrade-v1-v2.adoc
  docs/modules/ROOT/pages/how-tos/upgrade.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: change

#32 Fix release action to display "x commits to master since this release"
  .github/workflows/release.yaml
Labels: bug

#34 Update wrestic version to v0.3.2
  class/defaults.yml
Labels: dependency
