Repository projectsyn/component-backup-k8up, pull requests merged in 2022-07, with the labels that each got.

#93 Upgrade K8up chart to v3
  class/backup-k8up.yml
  class/defaults.yml
  component/app.jsonnet
  docs/modules/ROOT/pages/how-tos/upgrade-v3-v4.adoc
  docs/modules/ROOT/partials/nav.adoc
  tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/clusterrolebinding.yaml
  tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/deployment.yaml
  tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/operator-clusterrole.yaml
  tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/service.yaml
  tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/serviceaccount.yaml
  tests/golden/v2/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/user-clusterrole.yaml
  tests/golden/v2/backup-k8up/backup-k8up/02_k8up_crds.yaml
Labels: breaking

#95 Fix Helm chart dependency directory
  class/backup-k8up.yml
Labels: bug

#96 Restructure K8up image specification
  class/backup-k8up.yml
  class/defaults.yml
Labels: change
