Repository projectsyn/component-backup-k8up, pull requests merged in 2022-03, with the labels that each got.

#76 Fix not all legacy crd are mentioned in upgrade howto
  docs/modules/ROOT/pages/how-tos/upgrade-v2-v3.adoc
Labels: documentation

#80 Update modulesync config
  .sync.yml
Labels: ignore

#82 Update multi-instance advertisement for Commodore v0.14.0
  class/defaults.yml
Labels: change
