Repository projectsyn/component-backup-k8up, pull requests merged in 2024-06, with the labels that each got.

#135 Update ghcr.io/k8up-io/k8up Docker tag to v2.10.0
  class/defaults.yml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/deployment.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/02_k8up_crds.yaml
Labels: dependency

#136 Update Helm release k8up to v4.7.0
  class/defaults.yml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/cleanup-hook.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/clusterrolebinding.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/deployment.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/executor-clusterrole.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/operator-clusterrole.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/service.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/serviceaccount.yaml
Labels: dependency, bump:minor

#140 Add option to skip backups for PVCs that aren't explicitly annotated
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/deployment.yaml
Labels: change

#141 Add ArgoCD sync server-side apply for CRDs
  class/backup-k8up.yml
  component/crds.jsonnet
  tests/golden/defaults/backup-k8up/backup-k8up/02_k8up_crds.yaml
Labels: bug, bump:patch

#143 Fix misconfigured helm value for `skipWithoutAnnotation`
  class/defaults.yml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/deployment.yaml
Labels: bug, bump:patch
