Repository projectsyn/component-backup-k8up, pull requests merged in 2025-08, with the labels that each got.

#158 Support configuring TLS Options
  lib/backup-k8up.libjsonnet
Labels: enhancement, bump:minor

#160 Update Helm release k8up to v4.8.5
  class/defaults.yml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/crds/k8up.io_archives.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/crds/k8up.io_backups.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/crds/k8up.io_checks.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/crds/k8up.io_podconfigs.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/crds/k8up.io_prebackuppods.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/crds/k8up.io_prunes.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/crds/k8up.io_restores.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/crds/k8up.io_schedules.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/crds/k8up.io_snapshots.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/cleanup-hook.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/clusterrolebinding.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/deployment.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/executor-clusterrole.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/operator-clusterrole.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/service.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/serviceaccount.yaml
Labels: dependency, bump:patch, automerge

#155 Update ghcr.io/k8up-io/k8up Docker tag to v2.13.0
  class/defaults.yml
  tests/golden/defaults/backup-k8up/backup-k8up/01_k8up_helmchart/k8up/templates/deployment.yaml
  tests/golden/defaults/backup-k8up/backup-k8up/02_k8up_crds.yaml
Labels: dependency, bump:minor

#159 Fix definition of TLS Options
  lib/backup-k8up.libjsonnet
Labels: bug, bump:patch

#161 Change Secret to ConfigMap
  lib/backup-k8up.libjsonnet
Labels: bug, bump:patch
